#include <stdlib.h>
#include <subthemes.h>
#include <string.h>
#include <stdio.h>

const char* subthemes_math[] = {
    "adição e subtração de números inteiros",
    "multiplicação e divisão de números inteiros",
    "ordem das operações",
    "frações equivalentes",
    "adição e subtração de frações",
    "multiplicação e divisão de frações",
    "números decimais",
    "conversão entre frações e decimais",
    "porcentagem e descontos simples",
    "porcentagem no cotidiano",
    "proporções e regras de três simples",
    "múltiplos e divisores",
    "MMC e MDC em problemas",
    "números primos",
    "potenciação com números naturais",
    "radiciação simples",
    "propriedades da adição e multiplicação",
    "expressões numéricas simples",
    "valor absoluto",
    "conjuntos e subconjuntos simples",
    "localização no plano cartesiano",
    "medidas de comprimento e área",
    "perímetro de figuras planas",
    "área de quadrado e retângulo",
    "área de triângulo",
    "área do círculo",
    "unidades de medida (comprimento, massa, tempo)",
    "leitura de gráficos de barras",
    "leitura de gráficos de setores (pizza)",
    "média aritmética simples",
    "mediana e moda",
    "probabilidade básica com dados ou moedas",
    "noções de estatística no cotidiano",
    "ângulos retos, agudos e obtusos",
    "operações com ângulos",
    "classificação de triângulos",
    "soma dos ângulos internos de triângulos",
    "teorema de Pitágoras (básico)",
    "retas paralelas e transversais",
    "área de figuras compostas simples",
    "simetria e reflexão",
    "introdução à álgebra",
    "resolução de expressões algébricas simples",
    "uso da letra como incógnita",
    "equações do 1º grau simples",
    "resolução de equações com frações",
    "problemas com equações do 1º grau",
    "interpretação de gráficos de funções",
    "função do 1º grau no cotidiano",
    "sequências numéricas simples",
    "padrões e regularidades",
    "progressões aritméticas com diferença pequena",
    "planejamento financeiro simples",
    "juros simples introdutórios",
    "resolução de problemas com tabelas",
    "noções de simetria em figuras geométricas",
    "planificação de sólidos geométricos",
    "volume de cubo e paralelepípedo",
    "medidas de tempo e conversões",
    "leitura e interpretação de horários",
    "situações-problema com dinheiro",
    "probabilidade com cartas e roletas",
    "relações de proporcionalidade",
    "transformações geométricas básicas",
    "relações entre lados e ângulos em triângulos",
    "classificação dos quadriláteros",
    "semelhança de figuras geométricas simples",
    "análise combinatória básica (sem fórmula)",
    "problemas envolvendo escalas",
    "operações com números negativos",
    "representação de frações na reta numérica",
    "problemas envolvendo temperatura",
    "problemas com velocidade média",
    "razões no cotidiano",
    "cálculo de áreas somando e subtraindo figuras",
    "formas geométricas espaciais simples",
    "operações com medidas de tempo",
    "resolução de problemas com estimativas",
    "interpretação de tabelas de frequência",
    "leitura e interpretação de mapas e plantas",
    "conversão de unidades de medida de área",
    "cálculo de área com decomposição de figuras",
    "operações com expressões usando parênteses",
    "problemas com calendário",
    "sequência de padrões com figuras",
    "probabilidade de eventos simples",
    "operações com porcentagens consecutivas",
    "reconhecimento de gráficos de funções simples",
    "comparação de grandezas",
    "resolução de problemas de adivinhação com equações",
    "interpretação de informações matemáticas em texto",
    "resolução de problemas em etapas",
    "uso da matemática em receitas",
    "problemas matemáticos em jogos",
    "organização de dados em gráficos",
    "análise de situações cotidianas com porcentagem",
    "jogos matemáticos com operações básicas",
    "reconhecimento de regularidades em mosaicos",
    "estimativas e arredondamentos",
    "problemas envolvendo troco",
    "problemas de matemática financeira elementar",
    "aplicações do teorema de Pitágoras simples"
};

const int subthemes_math_count = sizeof(subthemes_math) / sizeof(subthemes_math[0]);

const char* subthemes_musics[] = {
    "notas musicais básicas",
    "escala musical natural",
    "instrumentos de corda",
    "instrumentos de sopro",
    "instrumentos de percussão",
    "instrumentos eletrônicos",
    "vozes masculinas e femininas",
    "principais estilos musicais",
    "ritmos populares do Brasil",
    "ritmos populares do mundo",
    "samba e sua origem",
    "forró e suas variações",
    "bossa nova e seus representantes",
    "rock nacional anos 80",
    "rock internacional clássico",
    "pop internacional atual",
    "artistas da MPB",
    "bandas de rock famosas",
    "cantores(as) pop dos anos 2000",
    "história do funk brasileiro",
    "características do sertanejo",
    "música clássica para iniciantes",
    "compositores clássicos famosos",
    "elementos da música (ritmo, melodia, harmonia)",
    "notação musical básica",
    "figuras rítmicas simples (semínima, mínima, colcheia)",
    "tempo e compasso musical",
    "leitura de partitura básica",
    "diferença entre ritmo e melodia",
    "o que é um refrão",
    "o que é um verso",
    "formato de uma música popular",
    "o que é um solo musical",
    "bandas de k-pop famosas",
    "principais vozes no coral",
    "principais instrumentos da orquestra",
    "papel do maestro",
    "músicas de filmes famosos",
    "trilhas sonoras icônicas",
    "músicas infantis conhecidas",
    "músicas natalinas populares",
    "canções de roda tradicionais",
    "danças típicas associadas à música",
    "história do hip hop",
    "grupos de rap famosos",
    "cantoras brasileiras de destaque",
    "cantores brasileiros de destaque",
    "bandas brasileiras de sucesso",
    "o que é um álbum musical",
    "diferença entre EP e LP",
    "música digital versus vinil",
    "plataformas de streaming musical",
    "hits mais populares da década de 2010",
    "prêmios musicais famosos (Grammy, VMA)",
    "curiosidades sobre os Beatles",
    "curiosidades sobre Elvis Presley",
    "curiosidades sobre Michael Jackson",
    "curiosidades sobre Anitta",
    "história do reggae",
    "história do jazz",
    "origem do blues",
    "ritmos latinos famosos (salsa, merengue)",
    "dança e música: capoeira",
    "música folclórica brasileira",
    "diferença entre DJ e produtor musical",
    "como funciona um autotune",
    "curiosidades sobre a música eletrônica",
    "música nos jogos eletrônicos",
    "música em novelas brasileiras",
    "principais trilhas sonoras de animes",
    "curiosidades sobre música em desenhos animados",
    "cifras e tablaturas básicas",
    "acordes maiores e menores",
    "famílias dos instrumentos musicais",
    "diferença entre agudo e grave",
    "diferença entre solo e dueto",
    "como é formado um trio musical",
    "função de um backing vocal",
    "influência da música africana no Brasil",
    "música indígena brasileira",
    "marchinhas de carnaval famosas",
    "bandas marciais e suas funções",
    "música gospel popular",
    "música sertaneja universitária",
    "diferença entre pop e rock",
    "o que é um hit musical",
    "caminho de uma música até o sucesso",
    "principais rádios de música no Brasil",
    "festivais de música famosos",
    "música e identidade cultural",
    "efeitos musicais em filmes de terror",
    "trilhas sonoras em filmes da Disney",
    "música no TikTok e redes sociais",
    "músicas que viralizaram na internet",
    "função da música em comerciais",
    "o que é playback",
    "quem foi Heitor Villa-Lobos",
    "curiosidades sobre Tom Jobim",
    "artistas brasileiros na Billboard",
    "música e esporte (hinos, trilhas)",
    "diferença entre cover e original",
    "música instrumental famosa",
    "compositores brasileiros contemporâneos",
    "música no contexto escolar"
};

const int subthemes_musics_count = sizeof(subthemes_musics) / sizeof(subthemes_musics[0]);

const char* subthemes_movies[] = {
    "a saga Harry Potter",
    "a trilogia Senhor dos Anéis",
    "a saga Star Wars",
    "a saga Crepúsculo",
    "a série de filmes Jogos Vorazes",
    "os filmes do universo Marvel",
    "os filmes do universo DC",
    "os filmes da Pixar",
    "os filmes clássicos da Disney",
    "os filmes da DreamWorks",
    "os filmes da Illumination",
    "os filmes de Quentin Tarantino",
    "os filmes de Steven Spielberg",
    "os filmes de Christopher Nolan",
    "os filmes de Tim Burton",
    "os filmes de Martin Scorsese",
    "os filmes de Alfred Hitchcock",
    "os filmes de James Cameron",
    "os filmes de Ridley Scott",
    "os filmes de Wes Anderson",
    "os filmes dirigidos por mulheres",
    "filmes baseados em livros",
    "filmes inspirados em fatos reais",
    "filmes com viagem no tempo",
    "filmes de distopia futurista",
    "filmes ambientados em escolas",
    "filmes que se passam no espaço",
    "filmes que se passam em um só local",
    "filmes de tribunal",
    "filmes de esporte",
    "filmes com animais protagonistas",
    "filmes com robôs ou inteligência artificial",
    "filmes de zumbis",
    "filmes de monstros gigantes",
    "filmes com vilões memoráveis",
    "filmes com duplas de protagonistas",
    "filmes com crianças como protagonistas",
    "filmes com trilha sonora marcante",
    "filmes de romance adolescente",
    "filmes de comédia romântica",
    "filmes de ação com perseguições",
    "filmes de guerra",
    "filmes de espionagem",
    "filmes de faroeste",
    "filmes de suspense psicológico",
    "filmes de terror sobrenatural",
    "filmes de terror slasher",
    "filmes de máfia ou crime organizado",
    "filmes de investigação policial",
    "filmes de sobrevivência na natureza",
    "filmes com histórias inspiradoras",
    "filmes com finais abertos",
    "filmes com narradores não confiáveis",
    "filmes mudos clássicos",
    "filmes vencedores do Oscar de melhor filme",
    "filmes indicados ao Globo de Ouro",
    "filmes vencedores em Cannes",
    "filmes cult",
    "filmes independentes premiados",
    "filmes dos anos 80",
    "filmes dos anos 90",
    "filmes dos anos 2000",
    "filmes lançados nos anos 2010",
    "filmes brasileiros famosos",
    "filmes de Bollywood",
    "filmes franceses premiados",
    "filmes japoneses de animação",
    "curtas-metragens famosos",
    "atores consagrados de Hollywood",
    "atrizes vencedoras do Oscar",
    "Leonardo DiCaprio e sua filmografia",
    "Tom Hanks e sua carreira",
    "Meryl Streep e seus papéis marcantes",
    "Sandra Bullock em comédias e dramas",
    "Keanu Reeves e seus personagens icônicos",
    "Johnny Depp em filmes excêntricos",
    "Emma Watson e seus papéis pós-Harry Potter",
    "Denzel Washington e seus filmes premiados",
    "Will Smith e suas atuações cômicas e dramáticas",
    "Natalie Portman e sua versatilidade",
    "Robin Williams em papéis emocionantes",
    "atores mirins famosos no cinema",
    "personagens femininas icônicas",
    "casais famosos do cinema",
    "amizades marcantes no cinema",
    "vilões clássicos do cinema",
    "anti-heróis em filmes populares",
    "filmes que viraram séries",
    "filmes que tiveram remakes",
    "filmes que foram rebootados",
    "trilogias famosas",
    "sagas com mais de três filmes",
    "filmes que viraram musicais",
    "filmes que se tornaram livros",
    "bastidores de grandes filmes",
    "filmes com cenas de improviso",
    "erros de gravação engraçados",
    "frases icônicas do cinema",
    "pôsteres de filmes famosos",
    "trailers que enganaram o público",
    "filmes lançados direto em streaming",
    "filmes que causaram polêmica",
    "filmes com grandes bilheterias",
    "filmes que fracassaram no lançamento",
    "estreias mais esperadas do cinema",
    "curiosidades do Oscar",
};

const int subthemes_movies_count = sizeof(subthemes_movies) / sizeof(subthemes_movies[0]);

const char* subthemes_general_knowledge[] = {
    "capitais dos países",
    "bandeiras nacionais",
    "idiomas oficiais ao redor do mundo",
    "principais rios do mundo",
    "maiores desertos da Terra",
    "cordilheiras e montanhas famosas",
    "mares e oceanos",
    "continentes e suas características",
    "geografia do Brasil",
    "estados e capitais brasileiras",
    "biomas brasileiros",
    "animais ameaçados de extinção",
    "invenções que mudaram o mundo",
    "descobrimentos históricos",
    "personagens históricos importantes",
    "guerras mundiais",
    "mitologias gregas e romanas",
    "religião e símbolos religiosos",
    "festas e tradições culturais",
    "alimentos típicos de diversos países",
    "costumes de diferentes culturas",
    "curiosidades sobre o corpo humano",
    "órgãos e funções do corpo humano",
    "sistemas do corpo humano",
    "descobertas científicas famosas",
    "cientistas renomados",
    "teorias da física clássica",
    "química do dia a dia",
    "símbolos da tabela periódica",
    "energia renovável e sustentável",
    "reciclagem e meio ambiente",
    "efeito estufa e aquecimento global",
    "datas comemorativas do calendário",
    "prêmios Nobel e seus vencedores",
    "personagens influentes da atualidade",
    "acontecimentos marcantes do século XXI",
    "organizações internacionais",
    "moedas e economia mundial",
    "tecnologias emergentes",
    "história da internet",
    "tecnologia dos celulares",
    "história dos videogames",
    "marcas famosas e seus slogans",
    "logotipos de empresas conhecidas",
    "moda ao longo das décadas",
    "invenções brasileiras",
    "curiosidades do espaço",
    "planetas do sistema solar",
    "astrofísica básica",
    "eventos astronômicos",
    "constelações famosas",
    "instrumentos musicais do mundo",
    "tipos de dança",
    "obras literárias famosas",
    "autores clássicos da literatura",
    "literatura brasileira",
    "idiomas extintos ou raros",
    "alimentos e culinária internacional",
    "curiosidades sobre esportes olímpicos",
    "esportes populares no mundo",
    "recordes do Guinness Book",
    "invenções e seus inventores",
    "pintores e obras famosas",
    "movimentos artísticos históricos",
    "arquitetura de monumentos famosos",
    "patrimônios da humanidade",
    "marcos históricos do Brasil",
    "governos e sistemas políticos",
    "formas de governo pelo mundo",
    "bandeiras curiosas e seu significado",
    "ilhas e arquipélagos famosos",
    "regiões mais frias do planeta",
    "locais mais quentes da Terra",
    "ilhas habitadas e inabitadas",
    "curiosidades sobre o Japão",
    "curiosidades sobre a Índia",
    "curiosidades sobre os Estados Unidos",
    "curiosidades sobre a África",
    "costumes da China",
    "tradições da Europa",
    "culturas indígenas brasileiras",
    "povos da antiguidade",
    "impérios antigos",
    "construções antigas do mundo",
    "enigmas históricos",
    "mistérios do oceano",
    "curiosidades sobre vulcões",
    "terremotos e tsunamis",
    "desastres naturais marcantes",
    "medicinas tradicionais do mundo",
    "formas alternativas de energia",
    "profissões diferentes no mundo",
    "curiosidades sobre o tempo e clima",
    "formas de transporte incomuns",
    "rituais de passagem em culturas",
    "superstições ao redor do mundo",
    "animais exóticos",
    "lugares abandonados famosos",
    "expedições e descobertas",
    "animais que brilham no escuro",
    "curiosidades sobre insetos",
    "tradições natalinas ao redor do mundo",
    "formas de escrita antigas",
    "sistemas de medida antigos",
    "história das olimpíadas",
};


const int subthemes_general_knowledge_count = sizeof(subthemes_general_knowledge) / sizeof(subthemes_general_knowledge[0]);

const char* subthemes_aed[] = {
    "o que é um algoritmo",
    "passos para criar um algoritmo",
    "algoritmos sequenciais",
    "algoritmos com decisões (if/else)",
    "uso de repetições (loops)",
    "diferença entre for e while",
    "variáveis em algoritmos",
    "entrada e saída de dados",
    "conceito de função",
    "funções simples e chamadas"
};


const int subthemes_aed_count = sizeof(subthemes_aed) / sizeof(subthemes_aed[0]);

const char* get_random_subtheme(Theme theme) {
    printf("get_random_subtheme chamado com tema: %d\n", theme);
    int index = 0;
    switch (theme) {
        case THEME_MATEMATICA:
            index = rand() % subthemes_math_count;
            printf("Tema MATEMATICA, índice selecionado: %d, subtema: \"%s\"\n", index, subthemes_math[index]);
            return subthemes_math[index];
        case THEME_MUSICA:
            index = rand() % subthemes_musics_count;
            printf("Tema MUSICA, índice selecionado: %d, subtema: \"%s\"\n", index, subthemes_musics[index]);
            return subthemes_musics[index];
        case THEME_FILMES:
            index = rand() % subthemes_movies_count;
            printf("Tema FILMES, índice selecionado: %d, subtema: \"%s\"\n", index, subthemes_movies[index]);
            return subthemes_movies[index];
        case THEME_CONHECIMENTOS_GERAIS:
            index = rand() % subthemes_general_knowledge_count;
            printf("Tema CONHECIMENTOS_GERAIS, índice selecionado: %d, subtema: \"%s\"\n", index, subthemes_general_knowledge[index]);
            return subthemes_general_knowledge[index];
        case THEME_AED:
            index = rand() % subthemes_aed_count;
            printf("Tema AED, índice selecionado: %d, subtema: \"%s\"\n", index, subthemes_aed[index]);
            return subthemes_aed[index];
        default:
            printf("AVISO: Tema inválido (%d) passado para get_random_subtheme. Retornando NULL.\n", theme);
            return NULL;
    }
}
